# .streamlit/secrets.toml

# 在这里填入你的默认配置
DEFAULT_API_KEY = "64ecb61e11c343e08586bf320edfac9b.M692wWjp74JJyBun"  # 你的 SiliconFlow 或 DeepSeek Key 或智谱清言4.5
DEFAULT_BASE_URL = "https://open.bigmodel.cn/api/paas/v4/"
DEFAULT_MODEL = "glm-4.5"